(* *********************************************************************)
(*                                                                     *)
(*              The Compcert verified compiler                         *)
(*                                                                     *)
(*          Xavier Leroy, INRIA Paris-Rocquencourt                     *)
(*                                                                     *)
(*  Copyright Institut National de Recherche en Informatique et en     *)
(*  Automatique.  All rights reserved.  This file is distributed       *)
(*  under the terms of the INRIA Non-Commercial License Agreement.     *)
(*                                                                     *)
(* *********************************************************************)

(** Translation from Mach to TriCore. *)

Require Archi.
Require Import Coqlib Errors.
Require Import AST Integers Floats Memdata.
Require Import Op Locations Mach Asm.
Require Import Machtyping.

Local Open Scope string_scope.
Local Open Scope error_monad_scope.

(** The code generation functions take advantage of several
  characteristics of the [Mach] code generated by earlier passes of the
  compiler, mostly that argument and result registers are of the correct
  types.  These properties are true by construction, but it's easier to
  recheck them during code generation and fail if they do not hold. *)

(** Extracting integer,float or address registers. *)

Definition ireg_of (r: mreg) : res dreg :=
  match preg_of r with DREG mr => OK mr | _ => Error(msg "Asmgen.ireg_of") end.

Definition freg_of (r: mreg) : res dreg :=
  match preg_of r with DREG mr => OK mr | _ => Error(msg "Asmgen.freg_of") end.

Definition areg_of (r: mreg) : res areg :=
  match preg_of r with AREG mr => OK mr | _ => Error(msg "Asmgen.areg_of") end.

Definition preg_rpair_of (p: rpair mreg) : rpair preg := map_rpair preg_of p.

Definition ireg_of_rpair (p: rpair mreg) : res dreg :=
  match p with One r => ireg_of r | _ => Error(msg "Asmgen.ireg_of_rpair") end.

Definition areg_of_rpair (p: rpair mreg) : res areg :=
  match p with One r => areg_of r | _ => Error(msg "Asmgen.ireg_of_rpair") end.

Definition iregs_of_rpair (r: rpair mreg) : res (dreg * dreg) :=
  match preg_rpair_of r with
  | Two (DREG r1) (DREG r2) =>  OK (r1, r2)
  | _ => Error (msg "Asmgen.iregs_of_rpair")
  end.

Lemma iregs_of_rpair_eq:
  forall hi lo p',
    iregs_of_rpair (Two hi lo) = OK p' -> preg_of hi = fst p' /\  preg_of lo = snd p'.
Proof.
  unfold iregs_of_rpair. unfold preg_rpair_of. simpl. intros.
  destruct (preg_of hi); inv H. destruct (preg_of lo); inv H1.
  split; reflexivity.
Qed.

Lemma iregs_of_rpair_eq':
  forall hi lo p',
    iregs_of_rpair (Two hi lo) = OK p' -> ireg_of hi = OK (fst p') /\  ireg_of lo = OK (snd p').
Proof.
  unfold iregs_of_rpair. unfold preg_rpair_of. simpl. intros.
  unfold ireg_of. destruct (preg_of hi); inv H. destruct (preg_of lo); inv H1.
  auto.
Qed.

(** Integer constant functions *)

Program Definition mk_sconst_n (n : { n: Z | 0 < n < 31 }) x : signed_const_n n :=
  {| s_amount := Int.sign_ext n x |}.
Next Obligation.
  split; try lia.
  assert (N_range: two_p (n-1) < Int.half_modulus).
  { change (Int.half_modulus) with (two_p 31). apply two_p_monotone_strict. lia. }
  exploit (Int.sign_ext_range n x). unfold Int.zwordsize ; simpl; lia.
  intros.
  unfold is_in_signed_range. apply andb_true_iff. split; apply zlt_true.
  rewrite Int.signed_repr. lia.
  unfold Int.min_signed, Int.max_signed. lia.
  rewrite Int.signed_repr. lia.
  unfold Int.min_signed, Int.max_signed. lia.
Qed.

Program Definition mk_sconst4 n : sconst4 := mk_sconst_n 4 n.
Next Obligation. lia. Qed.

Program Definition mk_sconst9 n : sconst9 := mk_sconst_n 9 n.
Next Obligation. lia. Qed.

Program Definition mk_sconst16 n : sconst16 := mk_sconst_n 16 n.
Next Obligation. lia. Qed.

Program Definition mk_uconst_n (n : { n: Z | 0 < n < 32 }) x : unsigned_const_n n :=
  {| u_amount := Int.zero_ext n x |}.
Next Obligation.
  split. unfold Int.ltu. apply zlt_true. rewrite Int.unsigned_repr.
  apply (Int.zero_ext_range n x). unfold Int.zwordsize; simpl; lia.
  unfold Int.max_unsigned. simpl. change (4294967295) with ((two_p 32) - 1).
  assert (two_p n <= two_p 31).
  assert (0 < n < 31 \/ n = 31). lia.
  destruct H.
  exploit (two_p_monotone_strict n 31). lia. lia.
  rewrite H. lia.
  split. exploit (two_p_strict n); lia.
  change 32 with (Z.succ 31).
  rewrite ZArith.Zpower.two_p_S. assert (two_p 31 > 1). compute. reflexivity.
  lia. lia.
  unfold Int.zwordsize; simpl; lia.
Qed.

Program Definition mk_uconst2 n: uconst2 := mk_uconst_n 2 n.
Next Obligation. lia. Qed.

Program Definition mk_uconst4 n: uconst4 := mk_uconst_n 4 n.
Next Obligation. lia. Qed.

Program Definition mk_uconst5 n: uconst5 := mk_uconst_n 5 n.
Next Obligation. lia. Qed.

Program Definition mk_uconst8 n : uconst8 := mk_uconst_n 8 n.
Next Obligation. lia. Qed.

Program Definition mk_uconst9 n : uconst9 := mk_uconst_n 9 n.
Next Obligation. lia. Qed.

Program Definition mk_uconst16 n : uconst16 := mk_uconst_n 16 n.
Next Obligation. lia. Qed.

Definition get_uconst2 n : option uconst2 :=
  if Int.ltu n (Int.repr 4) then
    Some (mk_uconst2 n)
  else 
    None.

Definition get_sconst4 n : option sconst4 :=
  if is_in_signed_range 4 n then
    Some (mk_sconst4 n)
  else
    None.

Definition get_uconst4 n : option uconst4 :=
  if Int.ltu n (Int.repr 16) then
    Some (mk_uconst4 n)
  else
    None.

Definition get_sconst9 n : option sconst9 :=
  if is_in_signed_range 9 n then
    Some (mk_sconst9 n)
  else
    None.

Definition get_sconst16 n : option sconst16 :=
  if is_in_signed_range 16 n then
    Some (mk_sconst16 n)
  else
    None.

Definition get_uconst9 n : option uconst9 :=
  if Int.ltu n (Int.repr (two_p 9)) then
    Some (mk_uconst9 n)
  else
    None.

Definition move_rr (rd r: dreg) (k: code) :=
  if dreg_eq rd r then
    k
  else
    Pmov rd r :: k.

Definition bit0 : uconst5 := mk_uconst5 Int.zero.
Definition bit1 : uconst5 := mk_uconst5 Int.one.
Definition bit2 : uconst5 := mk_uconst5 (Int.repr 2).

(** Decomposition of integer constants.  As noted in file [Asm],
  immediate arguments to TriCore instructions must fit into 16 bits,
  and are interpreted after zero extension, sign extension, or
  left shift by 16 bits, depending on the instruction.  Integer
  constants that do not fit must be synthesized using two
  processor instructions.  The following functions decompose
  arbitrary 32-bit integers into two 16-bit halves (high and low
  halves).  They satisfy the following properties:
- [low_u n] is an unsigned 16-bit integer;
- [low_s n] is a signed 16-bit integer;
- [(high_u n) << 16 | low_u n] equals [n];
- [(high_s n) << 16 + low_s n] equals [n].
*)

Definition low_s (n: int) := mk_sconst16 n.
Definition high_s (n: int) := mk_uconst16 (Int.shru (Int.sub n (low_s n)) (Int.repr 16)).

(** Smart constructors for arithmetic operations involving
  a 32-bit integer constant. Depending on whether the
  constant fits in the immediate offsets or not, one
  or several instructions are generated as required
  to perform the operation and prepended to the
  given instruction sequence [k]. *)

Definition loadimm (r: dreg) (n: int) (k: code) :=
  if Int.eq (high_s n) Int.zero then
    Pmovi r (low_s n) :: k
  else if Int.eq (low_s n) Int.zero then
    Pmovh r (high_s n) :: k
  else
    Pmovh r (high_s n) ::
    Paddi r r (low_s n) :: k.

Definition loadimm_addr (r:areg) (n:int) (k:code) :=
  if Int.eq (low_s n) Int.zero  (* No case for if the high bits are zero because there is no instruction to just set the low bits of an areg. *)
  then
    Pmovh_ao r (high_s n) :: k
  else
    Pmovh_ao r (high_s n) :: Plea_sc16 r r (low_s n):: k.
    

Definition select_encoding_instr
           (instr1: dreg -> dreg -> instruction)
           (instr2: dreg -> dreg -> dreg -> instruction)
           (commut: bool) (rd r1 r2: dreg) (k: code) :=
  if dreg_eq rd r1 then
    instr1 rd r2 :: k
  else if commut && dreg_eq rd r2 then
    instr1 rd r1 :: k
  else
    instr2 rd r1 r2 ::k.

Definition select_encoding_instr_aa
           (instr1: areg -> areg -> instruction)
           (instr2: areg -> areg -> areg -> instruction)
           (commut: bool) (rd r1 r2: areg) (k: code) :=
  if areg_eq rd r1 then
    instr1 rd r2 :: k
  else if commut && areg_eq rd r2 then
    instr1 rd r1 :: k
  else
    instr2 rd r1 r2 ::k.

Definition add (rd r1 r2: dreg) (k: code) :=
  select_encoding_instr Padd_rr Padd true rd r1 r2 k.

Definition add_aa (rd r1 r2: areg) (k: code) :=
  select_encoding_instr_aa Padd_aa Padd_a true rd r1 r2 k.

Definition add_d (rd r1: dreg) (r2: areg) (k: code): code :=
  if (dreg_eq rd r1) then
    Pmov_d TMP r2::Padd rd r1 TMP::k
  else
    Pmov_d rd r2:: Padd_rr rd r1::k.

Definition sub (rd r1 r2: dreg) (k: code) :=
  select_encoding_instr Psub_rr Psub false rd r1 r2 k.

Definition mul (rd r1 r2: dreg) (k: code) :=
  select_encoding_instr Pmul_rr Pmul true rd r1 r2 k.

Definition and (rd r1 r2: dreg) (k: code) :=
  select_encoding_instr Pand_rr Pand true rd r1 r2 k.

Definition or (rd r1 r2: dreg) (k: code) :=
  select_encoding_instr Por_rr Por true rd r1 r2 k.

Definition xor (rd r1 r2: dreg) (k: code) :=
  select_encoding_instr Pxor_rr Pxor true rd r1 r2 k.

(* Smart selection for unsigned 9 bit constants *)
Definition op_sc9
           (op1: sconst9 -> instruction)
           (op2: dreg -> code -> code)
           (n: int) (k: code) :=
  match get_sconst9 n with
  | Some imm => op1 imm :: k
  | None => loadimm TMP n (op2 TMP k)
  end.

Definition addimm_gen {T : Type}
  (add_low: T -> T -> sconst16 -> instruction)
  (add_high: T -> T -> uconst16  -> instruction)
  (rd r: T) (n: int) (k: code) :=
  if Int.eq (high_s n) Int.zero then
    add_low rd r (low_s n) :: k
  else if Int.eq (low_s n) Int.zero then
    add_high rd r (high_s n) :: k
  else
    add_high rd r (high_s n) :: add_low rd rd (low_s n) :: k.

Definition addimm (rd r: dreg) (n: int) (k: code) :=
  if dreg_eq rd r && is_in_signed_range 4 n then
    Padd_sc4 rd (mk_sconst4 n) :: k
  else addimm_gen Paddi Paddih rd r n k.

Definition addimm_addr (rd r: areg) (n: int) (k: code) :=
  if areg_eq rd r && is_in_signed_range 4 n then
    Padd_asc4 rd (mk_sconst4 n) :: k
  else
    addimm_gen Plea_sc16 Paddih_a rd r n k.

Definition rsubimm (rd r: dreg) (n: int) (k: code) :=
  if dreg_eq rd r && Int.eq n Int.zero then
    Prsub_r rd :: k
  else
    op_sc9 (Prsub rd r) (fun r' => sub rd r' r) n k.

Definition mulimm (rd r : dreg) (n:int) (k: code) :=
  op_sc9 (Pmul_sc9 rd r) (mul rd r) n k.

Definition slimm (rd r: dreg) (n: int) (k: code) :=
  if dreg_eq rd r && Int.ltu n (Int.repr 8) then
    Psh_sc4 rd (mk_sconst4 n) :: k
  else
    Psh_sc9 rd r (mk_sconst9 n) :: k.

Definition lsrimm (rd r: dreg) (n: amount32) (k: code) :=
  if dreg_eq rd r && (Int.ltu n (Int.repr 9)) then
    Psh_sc4 rd (mk_sconst4 (Int.neg n)) :: k
  else
    Psh_sc9 rd r (mk_sconst9 (Int.neg n)) :: k.

Definition asrimm (rd r: dreg) (n: amount32) (k: code) :=
  if dreg_eq rd r && (Int.ltu n (Int.repr 9)) then
    Psha_sc4 rd (mk_sconst4 (Int.neg n)) :: k
  else
    Psha_sc9 rd r (mk_sconst9 (Int.neg n)) :: k.

Definition maddimm (rd r1 r2: dreg) (n:int) (k:code) :=
  op_sc9 (Pmadd_sc9 rd r1 r2) (fun r3 k => Pmadd rd r1 r2 r3 :: k) n k.

Definition msubimm (rd r1 r2: dreg) (n:int) (k:code) :=
  op_sc9 (Pmsub_sc9 rd r1 r2) (fun r3 k => Pmsub rd r1 r2 r3 :: k) n k.

(* Smart selection for unsigned 9 byte constants *)
Definition op_uc9
           (op1: uconst9 -> instruction)
           (op2: dreg -> code -> code)
           (n: int) (k: code) :=
  match get_uconst9 n with
  | Some imm => op1 imm :: k
  | None => loadimm TMP n (op2 TMP k)
  end.

(* Smart selection for unsigned 9 byte constants with the
   additional case that an instruction exists which negates
   the constant *)
Definition op_uc9_not
           (op1: uconst9 -> instruction)
           (op1n: uconst9 -> instruction)
           (op2: dreg -> code -> code)
           (n: int) (k:code) :=
  match get_uconst9 (Int.not n) with
  | Some imm => op1n imm :: k
  | None => op_uc9 op1 op2 n k
  end.

Definition andimm (rd r: dreg) (n: int) (k: code) :=
  if dreg_eq rd r && dreg_eq rd D15 && Int.ltu n (Int.repr (two_p 8)) then
    Pand_d15uc8 (mk_uconst8 n) :: k
  else
    op_uc9_not (Pand_ruc9 rd r) (Pandn_uc9 rd r) (and rd r) n k.

Definition nandimm (rd r: dreg) (n: int) (k: code) :=
  op_uc9 (Pnand_uc9 rd r) (fun r2 k => Pnand rd r r2 :: k) n k.

Definition orimm (rd r: dreg) (n: int) (k: code) :=
  if dreg_eq rd r && dreg_eq rd D15 && Int.ltu n (Int.repr (two_p 8)) then
    Por_d15uc8 (mk_uconst8 n) :: k
  else
    op_uc9_not (Por_ruc9 rd r) (Porn_uc9 rd r) (or rd r) n k.

Definition norimm (rd r: dreg) (n: int) (k: code) :=
  op_uc9 (Pnor_uc9 rd r) (fun r2 k => Pnor rd r r2 :: k) n k.

Definition xorimm (rd r: dreg) (n: int) (k: code) :=
  op_uc9 (Pxor_ruc9 rd r) (xor rd r) n k.

Definition xnorimm (rd r: dreg) (n: int) (k:code) :=
  op_uc9 (Pxnor_uc9 rd r) (fun r2 k => Pxnor rd r r2 :: k) n k.

(** Translation of conditional branches. *)

Definition transl_cbranch_int32s (cmp: comparison) (r1 r2: dreg) (lbl: label) :=
  match cmp with
  | Ceq => Pjeq r1 r2 lbl
  | Cne => Pjne r1 r2 lbl
  | Clt => Pjlt r1 r2 lbl
  | Cle => Pjge r2 r1 lbl
  | Cgt => Pjlt r2 r1 lbl
  | Cge => Pjge r1 r2 lbl
  end.

Definition transl_cbranch_int32s_imm (cmp: comparison) (n: int) (r: dreg) (lbl: label) (k: code) :=
  let def := loadimm TMP n (transl_cbranch_int32s cmp r TMP lbl :: k) in
  match cmp with
  | Ceq =>
      match get_sconst4 n with
      | Some imm => Pjeq_sc4 r imm lbl :: k
      | None => def
      end
  | Cne =>
      match get_sconst4 n with
      | Some imm => Pjne_sc4 r imm lbl :: k
      | None => def
      end
  | Clt =>
      match get_sconst4 n with
      | Some imm => Pjlt_sc4 r imm lbl :: k
      | None => def
      end
  | Cge =>
      match get_sconst4 n with
      | Some imm => Pjge_sc4 r imm lbl :: k
      | None => def
      end
  | Cle =>
      if (Int.lt (Int.repr (-10)) n && Int.lt n (Int.repr 7)) then
        Pjlt_sc4 r (mk_sconst4 (Int.add n Int.one)) lbl :: k
      else
        def
  | Cgt =>
      if (Int.lt (Int.repr (-10)) n && Int.lt n (Int.repr 7)) then
        Pjge_sc4 r (mk_sconst4 (Int.add n Int.one)) lbl :: k
      else
        def
  end.

Definition transl_cbranch_int32u (cmp: comparison) (r1 r2: dreg) (lbl: label) :=
  match cmp with
  | Ceq => Pjeq r1 r2 lbl
  | Cne => Pjne r1 r2 lbl
  | Clt => Pjltu r1 r2 lbl
  | Cle => Pjgeu r2 r1 lbl
  | Cgt => Pjltu r2 r1 lbl
  | Cge => Pjgeu r1 r2 lbl
  end.

Definition transl_cbranch_int32u_imm (cmp: comparison) (n: int) (r: dreg) (lbl: label) (k: code) :=
  let def := loadimm TMP n (transl_cbranch_int32u cmp r TMP lbl :: k) in
  match cmp with
  | Ceq =>
      match get_sconst4 n with
      | Some imm => Pjeq_sc4 r imm lbl :: k
      | None => def
      end
  | Cne =>
      match get_sconst4 n with
      | Some imm => Pjne_sc4 r imm lbl :: k
      | None => def
      end
  | Clt =>
      match get_uconst4 n with
      | Some imm => Pjltu_sc4 r imm lbl :: k
      | None => def
      end
  | Cge =>
      match get_uconst4 n with
      | Some imm => Pjgeu_sc4 r imm lbl :: k
      | None => def
      end
  | Cle =>
      if Int.eq n Int.zero then
        Pjeq_sc4 r (mk_sconst4 Int.zero) lbl :: k
      else if Int.ltu n (Int.repr 15) then
        Pjltu_sc4 r (mk_uconst4 (Int.add n Int.one)) lbl :: k
      else
        def
  | Cgt =>
      if Int.ltu n (Int.repr 15) then
        Pjgeu_sc4 r (mk_uconst4 (Int.add n Int.one)) lbl :: k
      else
        def
  end.

Definition bit_of_cond_single (cmp: comparison) :=
  match cmp with
  | Ceq => (bit1, true)
  | Cne => (bit1, false)
  | Clt => (bit0, true)
  | Cle => (bit0, true)
  | Cgt => (bit2, true)
  | Cge => (bit0, true)
  end.

Definition transl_cond_single_branch (cmp: comparison) (rd r1 r2: dreg) (k: code) :=
  match cmp with
  | Cle =>
      Pcmpf rd r1 r2 :: Por_t rd rd bit1 rd bit0 :: k
  | Cge =>
      Pcmpf rd r1 r2 :: Por_t rd rd bit1 rd bit2 :: k
  | _ => Pcmpf rd r1 r2 :: k
  end.

Definition switch_A_D_via_TMP ar dr k :=Pmov TMP dr::Pmov_d dr ar::Pmov_a ar TMP::k.
Definition switch_A_D_via_TMPA ar dr k :=Pmov_a TMPA dr::Pmov_d dr ar::Pmov_aa ar TMPA::k.


Definition transl_cond_int32s (cmp: comparison) (rd r1 r2: dreg) :=
  match cmp with
  | Ceq => Peq rd r1 r2
  | Cne => Pne rd r1 r2
  | Clt => Plt rd r1 r2
  | Cle => Pge rd r2 r1
  | Cgt => Plt rd r2 r1
  | Cge => Pge rd r1 r2
  end.

Definition transl_condimm_int32s (cmp: comparison) (rd r: dreg) (n: int) (k: code) :=
  let def := loadimm TMP n (transl_cond_int32s cmp rd r TMP :: k) in
  match cmp with
  | Ceq =>
      match get_sconst9 n with
      | Some imm => Peq_sc9 rd r imm :: k
      | None => def
      end
  | Cne =>
      match get_sconst9 n with
      | Some imm => Pne_sc9 rd r imm :: k
      | None => def
      end
  | Clt =>
      match get_sconst9 n with
      | Some imm => Plt_sc9 rd r imm :: k
      | None => def
      end
  | Cge =>
      match get_sconst9 n with
      | Some imm => Pge_sc9 rd r imm :: k
      | None => def
      end
  | Cle =>
      if (Int.lt (Int.repr (-258)) n && Int.lt n (Int.repr 255)) then
        Plt_sc9 rd r (mk_sconst9 (Int.add n Int.one)) :: k
      else
        def
  | Cgt =>
      if (Int.lt (Int.repr (-258)) n && Int.lt n (Int.repr 255)) then
        Pge_sc9 rd r (mk_sconst9 (Int.add n Int.one)) :: k
      else
        def
  end.

Definition transl_cond_int32u (cmp: comparison) (rd r1 r2: dreg) :=
  match cmp with
  | Ceq => Peq rd r1 r2
  | Cne => Pne rd r1 r2
  | Clt => Pltu rd r1 r2
  | Cle => Pgeu rd r2 r1
  | Cgt => Pltu rd r2 r1
  | Cge => Pgeu rd r1 r2
  end.

Definition transl_cond_addr (cmp: comparison) (rd: dreg) (r1 r2: areg) :=
  match cmp with
  | Ceq => Peq_a rd r1 r2
  | Cne => Pne_a rd r1 r2
  | Clt => Pltu_a rd r1 r2
  | Cle => Pgeu_a rd r2 r1
  | Cgt => Pltu_a rd r2 r1
  | Cge => Pgeu_a rd r1 r2
  end.

Definition transl_condimm_int32u (cmp: comparison) (rd r: dreg) (n: int) (k: code) :=
  let def := loadimm TMP n (transl_cond_int32u cmp rd r TMP :: k) in
  match cmp with
  | Ceq =>
      match get_sconst9 n with
      | Some imm => Peq_sc9 rd r imm :: k
      | None => def
      end
  | Cne =>
      match get_sconst9 n with
      | Some imm => Pne_sc9 rd r imm :: k
      | None => def
      end
  | Clt =>
      match get_uconst9 n with
      | Some imm => Pltu_uc9 rd r imm :: k
      | None => def
      end
  | Cge =>
      match get_uconst9 n with
      | Some imm => Pgeu_uc9 rd r imm :: k
      | None => def
      end
  | Cle =>
      if Int.eq n Int.zero then
        Peq_sc9 rd r (mk_sconst9 Int.zero) :: k
      else if Int.ltu n (Int.repr 511) then
        Pltu_uc9 rd r (mk_uconst9 (Int.add n Int.one)) :: k
      else
        def
  | Cgt =>
      if Int.ltu n (Int.repr 511) then
        Pgeu_uc9 rd r (mk_uconst9 (Int.add n (Int.one))) :: k
      else
        def
  end.

(* TriCore contains instructions for comparing an address register to zero.
   Pointer-int comparisons semantically only work for (in)equality so we restrict ourselves to these cases. *)
Definition transl_condimm_addr (cmp: comparison) (rd: dreg) (r: areg) n : option instruction :=
  if Int.eq n Int.zero then 
    match cmp with
    | Ceq => Some (Peqz_a rd r)
    | Cne => Some (Pnez_a rd r)
    | _ => None
    end
  else None.

Definition bits_of_cond_single (cmp: comparison) :=
  match cmp with
  | Ceq => (bit1, bit1, true)
  | Cne => (bit1, bit1, false)
  | Clt => (bit0, bit0, true)
  | Cle => (bit0, bit1, true)
  | Cgt => (bit2, bit2, true)
  | Cge => (bit1, bit2, true)
  end.

Definition transl_cond_single_op (invert: bool) (cmp: comparison) (rd r1 r2: dreg) (k: code) :=
  let '(bit_1, bit_2, normal) := (bits_of_cond_single cmp) in
  let insn := if xorb normal invert then Por_t rd rd bit_1 rd bit_2 else Pnor_t rd rd bit_1 rd bit_2 in
  Pcmpf rd r1 r2 :: insn :: k.

Definition translate_bin_comp rd a1 a2 c k :=
  let transl_f := transl_cond_int32s c in
  let d := (if dreg_eq rd D2 then D3 else D2) in
  match preg_of a1, preg_of a2 with
  | AREG a1, AREG a2 => if areg_eq a1 a2
                       then
                         OK (Pmov_d TMP a1:: (transl_f rd TMP TMP)::k)
                       else
                         OK (switch_A_D_via_TMP a1 d (Pmov_d TMP a2:: (transl_f rd d TMP)::(switch_A_D_via_TMPA a1 d k)))
  | AREG a1, DREG r2 => OK (Pmov_d TMP a1:: (transl_f rd TMP r2)::k)
  | DREG r1, AREG a2 => OK (Pmov_d TMP a2:: (transl_f rd r1 TMP):: k)
  | DREG r1, DREG r2 =>  OK ((transl_f rd r1 r2) :: k)
  | _, _ => Error (msg " Trying to use special register for 2 register condition.")
  end.

(* In the case of unsigned comparison we can use special address register instructions from transl_cond_addr and
   avoid copying them into data registers. *)
Definition translate_bin_compu rd a1 a2 c k :=
  match preg_of a1, preg_of a2 with
  | AREG r1, AREG r2 => OK (transl_cond_addr c rd r1 r2 :: k)
  | AREG r1, DREG r2 => OK (Pmov_d TMP r1 :: transl_cond_int32u c rd TMP r2 :: k)
  | DREG r1, AREG r2 => OK (Pmov_d TMP r2 :: transl_cond_int32u c rd r1 TMP :: k)
  | DREG r1, DREG r2 =>  OK (transl_cond_int32u c rd r1 r2 :: k)
  | _, _ => Error (msg " Trying to use special register for 2 register condition.")
  end.

Definition translate_imm_comp rd (r:mreg) c n k :=
  let transl_f := transl_condimm_int32s c in
  match preg_of r with
  | AREG r => 
      if dreg_eq rd TMP
      then OK (switch_A_D_via_TMP r D2 (transl_f rd D2 n (switch_A_D_via_TMPA r D2 k)))
      else OK(Pmov_d rd r ::transl_f rd rd n k)
  | DREG r => OK(transl_f rd r n k)
  | _ => Error (msg "Trying to evaluate condition involving immediate using special register.")
  end.

(* In the case of unsigned comparison with an immediate we can use address register instructions from transl_condimm_addr_zero and
   avoid copying it into a data register. *)
Definition translate_imm_compu rd (r:mreg) cond n k :=
  match preg_of r with
  | AREG r => 
    match (transl_condimm_addr cond rd r n) with
    | Some c => OK (c :: k)
    | None => 
        if dreg_eq rd TMP
        then OK (switch_A_D_via_TMP r D2 (transl_condimm_int32u cond rd D2 n (switch_A_D_via_TMPA r D2 k)))
        else OK (Pmov_d rd r :: transl_condimm_int32u cond rd rd n k)
    end
  | DREG r => OK(transl_condimm_int32u cond rd r n k)
  | _ => Error (msg "Trying to evaluate condition involving immediate using special register.")
  end.
  
Definition transl_cond_op
           (cond: condition) (rd: dreg) (args: list mreg)  (k: code) :=
  match cond, args with
  | Ccomp c, a1 :: a2 :: nil => translate_bin_comp rd a1 a2 c k
  | Ccompu c, a1 :: a2 :: nil => translate_bin_compu rd a1 a2 c k
  | Ccompimm c n, a1 :: nil => translate_imm_comp rd a1 c n k
  | Ccompuimm c n, a1 :: nil => translate_imm_compu rd a1 c n k
  | Ccompfs c, f1 :: f2 :: nil =>
      do r1 <- ireg_of f1; do r2 <- ireg_of f2;
      OK (transl_cond_single_op false c rd r1 r2 k)
  | Cnotcompfs c, f1 :: f2 :: nil =>
      do r1 <- ireg_of f1; do r2 <- ireg_of f2;
      OK (transl_cond_single_op true c rd r1 r2 k)
  | Ccompf c, _ =>
    Error (msg "Double comparison not supported")
  | Cnotcompf c, _ =>
    Error (msg "Double comparison not supported")
  | _, _ =>
      Error(msg "Asmgen.transl_cond_branch")
  end.

Definition translate_bin_cbranch r1 r2 cond transl_f (lbl: label) k :=
  let d :=  D2 in
  match preg_of r1, preg_of r2 with
  | AREG a1, AREG a2 => if areg_eq a1 a2
                       then
                         OK (Pmov_d TMP a1:: (transl_f TMP TMP lbl)::k)
                       else
                         transl_cond_op cond TMP (r1::r2::nil) ((Pjne_sc4 TMP (mk_sconst4 Int.zero) lbl)::k)
                                        
  | AREG a1, DREG r2 => OK (Pmov_d TMP a1:: (transl_f TMP r2 lbl)::k)
  | DREG r1, AREG a2 => OK (Pmov_d TMP a2:: (transl_f r1 TMP lbl):: k)
  | DREG r1, DREG r2 =>  OK ((transl_f r1 r2 lbl) :: k)
  | _, _ => Error (msg " Trying to use special register for 2 register branch")
  end.

Definition transl_cbranch
           (cond: condition) (args: list mreg) (lbl: label) (k: code) :=
  match cond, args with
  | Ccomp c, a1 :: a2 :: nil => translate_bin_cbranch a1 a2 cond (transl_cbranch_int32s c) lbl k
  | Ccompu c, a1 :: a2 :: nil => translate_bin_cbranch a1 a2 cond (transl_cbranch_int32u c) lbl k
  | Ccompimm c n, a1 :: nil =>  match preg_of a1 with
                              | AREG a => transl_cond_op cond TMP (a1::nil) ((Pjne_sc4 TMP (mk_sconst4 Int.zero) lbl)::k)
                                            
                              | DREG d => OK(transl_cbranch_int32s_imm c n d lbl k)
                                           
                              | _ => Error (msg "Trying to evaluate condition involving immediate using special register.")                                     
                              end
  | Ccompuimm c n, a1 :: nil => match preg_of a1 with
                              | AREG a => transl_cond_op cond TMP (a1::nil) ((Pjne_sc4 TMP (mk_sconst4 Int.zero) lbl)::k)                               
                              | DREG d =>  OK (transl_cbranch_int32u_imm c n d lbl k)
                              | _ => Error (msg "Trying to evaluate condition involving immediate using special register.")                                     
                              end
     
  | Ccompfs c, f1 :: f2 :: nil =>
      do r1 <- ireg_of f1; do r2 <- ireg_of f2;
      let (bit, normal) := bit_of_cond_single c in
      let insn := if normal then Pjnz_t TMP bit lbl else Pjz_t TMP bit lbl in
      OK (transl_cond_single_branch c TMP r1 r2 (insn :: k))
  | Cnotcompfs c, f1 :: f2 :: nil =>
      do r1 <- ireg_of f1; do r2 <- ireg_of f2;
      let (bit, normal) := bit_of_cond_single c in
      let insn := if normal then Pjz_t TMP bit lbl else Pjnz_t TMP bit lbl in
      OK (transl_cond_single_branch c TMP r1 r2 (insn :: k))
  | Ccompf c, _ =>
    Error (msg "Double comparison not supported")
  | Cnotcompf c, _ =>
    Error (msg "Double comparison not supported")
  | _, _ =>
      Error(msg "Asmgen.transl_cond_branch")
  end.
  
Definition transl_op
           (op: operation) (args: list (rpair mreg)) (res: (rpair mreg)) (k: code) :=
   match op, args with
   | Omove, a1 :: nil =>
       match preg_rpair_of res, preg_rpair_of a1 with
       | One (DREG res), One (DREG a1) => OK (Pmov res a1 :: k)
       | One (AREG res), One (AREG a1) => OK (Pmov_aa res a1 :: k)
       | One (AREG res), One (DREG a1) => OK (Pmov_a res a1 :: k)
       | One (DREG res), One (AREG a1) => OK (Pmov_d res a1 :: k)
       | _, _ => Error (msg "Asmgen.Omove")
       end
   | Ointconst n, nil =>
       match preg_rpair_of res with
       | One (DREG rd) => OK (loadimm rd n k)
       | One (AREG rd) => OK (loadimm_addr rd n k)
       | _ => Error (msg "Trying to load int constant to special register")
       end
   | Osingleconst n, nil =>
       do rd <- ireg_of_rpair res;
       OK (Ploadsi rd n :: k)
   | Oaddrsymbol s ofs, nil =>
       match preg_rpair_of res with
       | One (AREG rd) => OK (Pmovh_sa rd s ofs :: Plea_sofs rd rd s ofs :: k)
       | One (DREG rd) => OK (Pmovh_s rd s ofs:: Paddi_ls rd rd s ofs::k)
       | _ => Error (msg "Trying to use special register as destination for Oaddrsymbol")
       end
   | Oaddrstack ofs, nil =>
       match (preg_rpair_of res) with
       | One (AREG rd) => OK (addimm_addr rd SP (Ptrofs.to_int ofs) k)
       | One (DREG rd) => OK (addimm_addr TMPA SP (Ptrofs.to_int ofs) (Pmov_d rd TMPA::k))
       | _ => Error (msg "Trying to use special register as destination for Oaddrstack")
       end
   | Opcast, r::nil =>
       do r_res <- areg_of_rpair res;
       match preg_rpair_of r with
       | One (DREG r') => OK (Pmov_a r_res r'::k)
       | One (AREG r') => OK (Pmov_aa r_res r'::k)
       | _ => Error (msg "Opcast of a register that should not be used in the program.")
       end
   | Oadd, a1 :: a2 :: nil =>
       match preg_rpair_of res with
       | One (DREG rd) =>
          do r1 <- ireg_of_rpair a1;
          do r2 <- ireg_of_rpair a2;
          OK (add rd r1 r2 k)
       | One (AREG rd) =>
          do r1 <- areg_of_rpair a1;
          do r2 <- ireg_of_rpair a2;
          OK (Paddsc_a rd r1 r2 (mk_uconst2 Int.zero) :: k)
       | _ => Error (msg "Trying to add data using registers that are not allowed to be used for addition.")
       end
   | Oaddl, a1 :: a2 :: nil =>
       do (rh, rl) <- iregs_of_rpair res;
       assertion (negb (dreg_eq rh rl));
       do (ah, al) <- iregs_of_rpair a1;
       do (bh, bl) <- iregs_of_rpair a2;
       if dreg_eq rl ah || dreg_eq rl bh then
         OK (Paddx TMP al bl :: Paddc rh ah bh :: Pmov rl TMP :: k)
       else
         OK (Paddx rl al bl :: Paddc rh ah bh :: k)
   | Oaddimm imm, a1 :: nil =>
       match preg_rpair_of res with
       | One (DREG rd) => do r1 <- ireg_of_rpair a1; OK (addimm rd r1 imm k)
       | One (AREG rd) => do r1 <- areg_of_rpair a1; OK (addimm_addr rd r1 imm k)
       | _ => Error (msg "Trying to add immediate using register that is not allowed to be used for addition")
       end
   | Osub, a1 :: a2 :: nil =>
       do rd <- ireg_of_rpair res;
       match preg_rpair_of a1 with
       | One (DREG r1) =>
          do r2 <- ireg_of_rpair a2;
          OK (sub rd r1 r2 k)
       | One (AREG r1) =>
          do r2 <- areg_of_rpair a2;
          OK (Psub_a TMPA r1 r2 :: Pmov_d rd TMPA :: k)
       | _ => Error (msg "Trying to sub data using registers that are not allowed to be used for subtraction.")
       end
   | Osubl, a1 :: a2 :: nil =>
       do (rh, rl) <- iregs_of_rpair res;
       assertion (negb (dreg_eq rh rl));
       do (ah, al) <- iregs_of_rpair a1;
       do (bh, bl) <- iregs_of_rpair a2;
       if dreg_eq rl ah || dreg_eq rl bh then
         OK (Psubx TMP al bl :: Psubc rh ah bh :: Pmov rl TMP :: k)
       else
         OK (Psubx rl al bl :: Psubc rh ah bh :: k)
   | Orsubimm imm, a1 :: nil =>
       do r1 <- ireg_of_rpair a1; do rd <- ireg_of_rpair res;
       OK (rsubimm rd r1 imm k)
   | Oneg, a1 :: nil =>
       do r <- ireg_of_rpair a1; do rd <- ireg_of_rpair res;
       OK (move_rr rd r (Prsub_r rd :: k))
   | Onegl, a1 :: nil =>
       do (rh, rl) <- iregs_of_rpair res;
       assertion (negb (dreg_eq rh rl));
       do (ah, al) <- iregs_of_rpair a1;
       if dreg_eq rl ah then
         OK (Prsub TMP al (mk_sconst9 Int.zero) :: Prsub rh ah (mk_sconst9 Int.zero) :: Pcadd_sc9 rh TMP rh (mk_sconst9 Int.mone) :: Pmov rl TMP :: k)
       else
         OK (Prsub rl al (mk_sconst9 Int.zero) :: Prsub rh ah (mk_sconst9 Int.zero) :: Pcadd_sc9 rh rl rh (mk_sconst9 Int.mone) :: k)
   | Omul, a1 :: a2 :: nil =>
       do r1 <- ireg_of_rpair a1; do r2 <- ireg_of_rpair a2; do rd <- ireg_of_rpair res;
       OK (mul rd r1 r2 k)
   | Omulimm imm, a1 :: nil =>
       do r1 <- ireg_of_rpair a1; do rd <- ireg_of_rpair res;
       OK (mulimm rd r1 imm k)
   | Omulhs, a1 :: a2 :: nil =>
       do rd <- ireg_of_rpair res;
       do r1 <- ireg_of_rpair a1;
       do r2 <- ireg_of_rpair a2;
       assertion (dreg_eq rd D5);
       OK (Pmul_e r1 r2 :: k)
   | Omulhu, a1 :: a2 :: nil =>
       do rd <- ireg_of_rpair res;
       do r1 <- ireg_of_rpair a1;
       do r2 <- ireg_of_rpair a2;
       assertion (dreg_eq rd D5);
       OK (Pmulu r1 r2 :: k)
   | Omulu, a1 :: a2 :: nil =>
       do r1 <- ireg_of_rpair a1;
       do r2 <- ireg_of_rpair a2;
       do (rh, rl) <- iregs_of_rpair res;
       assertion (dreg_eq rh D5);
       assertion (dreg_eq rl D4);
       OK (Pmulu r1 r2 :: k)
   | Omadd, a1 :: a2 :: a3 :: nil =>
       do r2 <- ireg_of_rpair a2; do r3 <- ireg_of_rpair a3; do rd <- ireg_of_rpair res;
        match (preg_rpair_of a1) with
        | One (DREG r1) => OK (Pmadd rd r1 r2 r3 :: k)
        | One (AREG a1) => OK (Pmov_d TMP a1::Pmadd rd TMP r2 r3::k)
        | _ => Error (msg "Trying to use special register in Omadd")
        end
   | Omaddimm imm, a1 :: a2 :: nil =>
       match preg_rpair_of res with
       | One (DREG rd) =>
         (* We know that a1 and res are the same register kind, and that a2 is a dreg. *)
         do r1 <- ireg_of_rpair a1;
         do r2 <- ireg_of_rpair a2;
         OK (maddimm rd r1 r2 imm k)
       | One (AREG rd) =>
         (* We know that a1 and res are the same register kind, and that a2 is a dreg. *)
         do r1 <- areg_of_rpair a1;
         do r2 <- ireg_of_rpair a2;
           match Int.is_power2 imm with
           | Some exp => match get_uconst2 exp with
                         | Some n => OK (Paddsc_a rd r1 r2 n :: k)
                         | None => OK (mulimm TMP r2 imm (Paddsc_a rd r1 TMP (mk_uconst2 Int.zero) :: k))
                         end
           | None => OK (mulimm TMP r2 imm (Paddsc_a rd r1 TMP (mk_uconst2 Int.zero) :: k))
           end
       | _ => Error (msg "Trying to use special register in Omaddimm")
       end
   | Omsub, a1 :: a2 :: a3 :: nil =>
       do r2 <- ireg_of_rpair a2; do r3 <- ireg_of_rpair a3; do rd <- ireg_of_rpair res;
       match (preg_rpair_of a1) with
       | One (DREG r1) => OK (Pmsub rd r1 r2 r3 :: k)
       | One (AREG a1) => OK (Pmov_d TMP a1::Pmsub rd TMP r2 r3::k)
       | _ => Error (msg "Trying to use special register in Omsub")
       end
   | Omsubimm imm, a1 :: a2 :: nil =>
       do r2 <- ireg_of_rpair a2; do rd <- ireg_of_rpair res;
       match (preg_rpair_of a1) with
       | One (DREG r1) => OK (msubimm rd r1 r2 imm k)
       | One (AREG r1) => if (dreg_eq rd r2)
                   then OK (mulimm TMP r2 imm (Pmov_d rd r1::Psub_rr rd TMP::k))
                   else
                     OK (Pmov_d rd r1:: msubimm rd rd r2 imm k)
       | _ => Error (msg "Trying to use special register in Omsubimm")
       end
   | Odiv, a1 :: a2 :: nil =>
       do r1 <- ireg_of_rpair a1; do r2 <- ireg_of_rpair a2; do rd <- ireg_of_rpair res;
       assertion (dreg_eq rd D4);
       OK (Pdiv r1 r2 :: k)
   | Odivu, a1 :: a2 :: nil =>
       do r1 <- ireg_of_rpair a1; do r2 <- ireg_of_rpair a2; do rd <- ireg_of_rpair res;
       assertion (dreg_eq rd D4);
       OK (Pdivu r1 r2 :: k)
   | Omod, a1 :: a2 :: nil =>
       do r1 <- ireg_of_rpair a1; do r2 <- ireg_of_rpair a2; do rd <- ireg_of_rpair res;
       assertion (dreg_eq rd D5);
       OK (Pdiv r1 r2 :: k)
   | Omodu, a1 :: a2 :: nil =>
       do r1 <- ireg_of_rpair a1; do r2 <- ireg_of_rpair a2; do rd <- ireg_of_rpair res;
       assertion (dreg_eq rd D5);
       OK (Pdivu r1 r2 :: k)
   | Onot, a1 :: nil =>
       do r <- ireg_of_rpair a1; do rd <- ireg_of_rpair res;
       OK (move_rr rd r (Pnot rd :: k))
   | Oand, a1 :: a2 :: nil =>
       do r1 <- ireg_of_rpair a1; do r2 <- ireg_of_rpair a2; do rd <- ireg_of_rpair res;
       OK (and rd r1 r2 k)
   | Oandimm n, a1 :: nil =>
       do rd <- ireg_of_rpair res;
       match (preg_rpair_of a1) with
       | One (DREG r1) => OK (andimm rd r1 n k)
       | One (AREG r1) => OK (Pmov_d rd r1:: andimm rd rd n k)
       | _ => Error (msg "Trying to use Oandimm with special register")
       end
   | Oandn, a1 :: a2 :: nil =>
       do r1 <- ireg_of_rpair a1; do r2 <- ireg_of_rpair a2; do rd <- ireg_of_rpair res;
       OK (Pandn rd r1 r2 :: k)
   | Onand, a1 :: a2 :: nil =>
       do r1 <- ireg_of_rpair a1; do r2 <- ireg_of_rpair a2; do rd <- ireg_of_rpair res;
       OK (Pnand rd r1 r2 :: k)
   | Onandimm n, a1 :: nil =>
       do r1 <- ireg_of_rpair a1; do rd <- ireg_of_rpair res;
       OK (nandimm rd r1 n k)
   | Oor, a1 :: a2 :: nil =>
       do r1 <- ireg_of_rpair a1; do r2 <- ireg_of_rpair a2; do rd <- ireg_of_rpair res;
       OK (or rd r1 r2 k)
   | Oorimm n, a1 :: nil =>
       do rd <- ireg_of_rpair res;
       match (preg_rpair_of a1) with
       | One (DREG r1) => OK (orimm rd r1 n k)
       | One (AREG r1) => OK (Pmov_d rd r1::(orimm rd rd n k))
       | _ => Error (msg " Trying to use special register with Oorimm")
       end
   | Oorn, a1 :: a2 :: nil =>
       do r1 <- ireg_of_rpair a1; do r2 <- ireg_of_rpair a2; do rd <- ireg_of_rpair res;
       OK (Porn rd r1 r2 :: k)
   | Onor, a1 :: a2 :: nil =>
       do r1 <- ireg_of_rpair a1; do r2 <- ireg_of_rpair a2; do rd <- ireg_of_rpair res;
       OK (Pnor rd r1 r2 :: k)
   | Onorimm n, a1 :: nil =>
       do r1 <- ireg_of_rpair a1; do rd <- ireg_of_rpair res;
       OK (norimm rd r1 n k)
   | Oxor, a1 :: a2 :: nil =>
       do r1 <- ireg_of_rpair a1; do r2 <- ireg_of_rpair a2; do rd <- ireg_of_rpair res;
       OK (xor rd r1 r2 k)
   | Oxorimm n, a1 :: nil =>
       do r1 <- ireg_of_rpair a1; do rd <- ireg_of_rpair res;
       OK (xorimm rd r1 n k)
   | Oxnor, a1 :: a2 :: nil =>
       do r1 <- ireg_of_rpair a1; do r2 <- ireg_of_rpair a2; do rd <- ireg_of_rpair res;
       OK (Pxnor rd r1 r2 :: k)
   | Oxnorimm n, a1 :: nil =>
       do r1 <- ireg_of_rpair a1; do rd <- ireg_of_rpair res;
       OK (xnorimm rd r1 n k)
   | Osl, a1 :: a2 :: nil =>
       do r1 <- ireg_of_rpair a1; do r2 <- ireg_of_rpair a2; do rd <- ireg_of_rpair res;
       OK (Psh rd r1 r2 :: k)
   | Oslimm n, a1 :: nil =>
       do r1 <- ireg_of_rpair a1; do rd <- ireg_of_rpair res;
       OK (slimm rd r1 n k)
   | Oasr, a1 :: a2 :: nil =>
       do r1 <- ireg_of_rpair a1; do r2 <- ireg_of_rpair a2; do rd <- ireg_of_rpair res;
       OK (Prsub D0 r2 (mk_sconst9 Int.zero) :: Psha rd r1 D0 :: k)
   | Oasrimm n, a1 :: nil =>
       do r1 <- ireg_of_rpair a1; do rd <- ireg_of_rpair res;
       OK (asrimm rd r1 n k)
   | Olsr, a1 :: a2 :: nil =>
       do r1 <- ireg_of_rpair a1; do r2 <- ireg_of_rpair a2; do rd <- ireg_of_rpair res;
       OK (Prsub D0 r2 (mk_sconst9 Int.zero) :: Psh rd r1 D0 :: k)
   | Olsrimm n, a1 :: nil =>
       do r1 <- ireg_of_rpair a1; do rd <- ireg_of_rpair res;
       OK (lsrimm rd r1 n k)
   | Oshrximm n, a1 :: nil =>
       do rd <- ireg_of_rpair res; do rs <- ireg_of_rpair a1;
       OK(if Int.eq n Int.zero then Pmov rd rs :: k else
          Psha_sc9 TMP rs (mk_sconst9 (Int.neg (Int.repr 31))) ::
          Psh_sc9 TMP TMP (mk_sconst9 (Int.neg (Int.sub Int.iwordsize n))) ::
          Padd TMP rs TMP ::
          Psha_sc9 rd TMP (mk_sconst9 (Int.neg n)) :: k)
   | Oextr pos width, a :: nil =>
       do r <- ireg_of_rpair a; do rd <- ireg_of_rpair res;
       OK (Pextr rd r (mk_uconst5 pos) (mk_uconst5 width) :: k)
   | Oextru pos width, a :: nil =>
       do r <- ireg_of_rpair a; do rd <- ireg_of_rpair res;
       OK (Pextru rd r (mk_uconst5 pos) (mk_uconst5 width) :: k)
   | Oinsert pos width, a1 :: a2 :: nil =>
       do r1 <- ireg_of_rpair a1; do r2 <- ireg_of_rpair a2; do rd <- ireg_of_rpair res;
       OK (Pinsert rd r1 r2 (mk_uconst5 pos) (mk_uconst5 width) :: k)
   | Osel ty, c :: a1 :: a2 :: nil => (* Note that ty has type typ and not argtype, hence Taptr is not an option. Hence the result type is also never Taptr and res should always be a data register. *)
       do rd <- ireg_of_rpair res;
       do c <- ireg_of_rpair c;
       let d := (if dreg_eq rd D2 then D3 else D2) in
       match (preg_rpair_of a1), (preg_rpair_of a2) with
       | One (DREG d1), One (DREG d2) => OK (Psel rd c d1 d2 :: k)
       | One (DREG d1), One (AREG a2) => OK (Pmov_d TMP a2 :: Psel rd c d1 TMP :: k)
       | One (AREG a1), One (DREG d2) => OK (Pmov_d TMP a1 :: Psel rd c TMP d2 :: k)
       | One (AREG a1), One (AREG a2) => if (areg_eq a1 a2)
                            then
                              OK (Pmov_d rd a1::k)
                            else if (dreg_eq rd c) then
                              OK (switch_A_D_via_TMP a1 d (Pmov_d TMP a2:: Psel rd rd d TMP::switch_A_D_via_TMP a1 d k))
                            else
                              OK (Pmov_d rd a1 :: Pmov_d TMP a2 :: Psel rd c rd TMP :: k)
       | _, _ => Error (msg "Trying to use special register in selection.")
       end
   | Ocadd, a1 :: a2 :: a3 :: nil =>
       do rd <- ireg_of_rpair res;
       do r1 <- ireg_of_rpair a1;
       do r2 <- ireg_of_rpair a2;
       do r3 <- ireg_of_rpair a3;
       OK (Pcadd rd r1 r2 r3 :: k)
   | Ocsub, a1 :: a2 :: a3 :: nil =>
       do rd <- ireg_of_rpair res;
       do r1 <- ireg_of_rpair a1;
       do r2 <- ireg_of_rpair a2;
       do r3 <- ireg_of_rpair a3;
       OK (Pcsub rd r1 r2 r3 :: k)
   | Ocmp cmp, _ =>
      do rd <- ireg_of_rpair res;
      do args <- mmap (@error_single mreg) args;
      transl_cond_op cmp rd args k
   | Onegfs, a :: nil =>
       do r <- ireg_of_rpair a; do rd <- ireg_of_rpair res;
       OK (Pnegf rd r :: k)
   | Oabsfs, a :: nil =>
       do r <- ireg_of_rpair a; do rd <- ireg_of_rpair res;
       OK (Pabsf rd r :: k)
   | Oaddfs, a1 :: a2 :: nil =>
       do r1 <- ireg_of_rpair a1; do r2 <- ireg_of_rpair a2; do rd <- ireg_of_rpair res;
       OK (Paddf rd r1 r2 :: k)
   | Osubfs, a1 :: a2 :: nil =>
       do r1 <- ireg_of_rpair a1; do r2 <- ireg_of_rpair a2; do rd <- ireg_of_rpair res;
       OK (Psubf rd r1 r2 :: k)
   | Omulfs, a1 :: a2 :: nil =>
       do r1 <- ireg_of_rpair a1; do r2 <- ireg_of_rpair a2; do rd <- ireg_of_rpair res;
       OK (Pmulf rd r1 r2 :: k)
   | Odivfs, a1 :: a2 :: nil =>
       do r1 <- ireg_of_rpair a1; do r2 <- ireg_of_rpair a2; do rd <- ireg_of_rpair res;
       OK (Pdivf rd r1 r2 :: k)
   | Ointofsingle, a :: nil =>
       do r <- ireg_of_rpair a; do rd <- ireg_of_rpair res;
       OK (Pftoiz rd r :: k)
   | Ointuofsingle, a :: nil =>
       do r <- ireg_of_rpair a; do rd <- ireg_of_rpair res;
       OK (Pftouz rd r :: k)
   | Osingleofint, a :: nil =>
       do r <- ireg_of_rpair a; do rd <- ireg_of_rpair res;
       OK (Pitof rd r :: k)
   | Osingleofintu, a :: nil =>
       do r <- ireg_of_rpair a; do rd <- ireg_of_rpair res;
       OK (Putof rd r :: k)
   | Ofloatconst n, _ =>
     Error (msg "Floatconst for double is not supported")
   | Onegf, _ =>
     Error (msg "Neg for double is not supported")
   | Oabsf, _ =>
     Error (msg "Absf for double is not supported")
   | Oaddf, _ =>
     Error (msg "Addf for double is not supported")
   | Osubf, _ =>
     Error (msg "Subf for double is not supported")
   | Omulf, _ =>
     Error (msg "Mulf for double is not supported")
   | Odivf, _ =>
     Error (msg "Divf for double is not supported")
   | Osingleoffloat, _ =>
     Error (msg "Single to dobule conversion is not supported")
   | Ofloatofsingle, _ =>
     Error (msg "Double to single conversion is not supported")
   | Ointoffloat, _ =>
     Error (msg "Double to signed int conversion is not supported")
   | Ointuoffloat, _ =>
     Error (msg "Double to unsigned int conversion is not supported")
   | Ofloatofint, _ =>
     Error (msg "Signed int to double conversion is not supported")
   | Ofloatofintu, _ =>
     Error (msg "Unsigned int to double conversion is not supported")
   | _,_ => Error(msg "Asmgen.transl_op")
   end.

(** Accessing data in the stack frame. *)

Definition indexed_memory_access
           (mk1_instr: areg -> instruction)
           (mk2_instr: index_reg -> sconst16 -> instruction)
           (base: index_reg) (ofs: ptrofs) (k: code) :=
  if Ptrofs.eq ofs Ptrofs.zero then
    mk1_instr base :: k
  else
    match get_sconst16 (Ptrofs.to_int ofs) with
    | Some ofs' =>
        mk2_instr base ofs' :: k
    | None =>
        let ofs := Ptrofs.to_int ofs in
        addimm_addr TMPA base ofs (mk1_instr TMPA :: k)
  end.

Definition loadind (base: index_reg) (ofs: ptrofs) (ty: typ) (dst: mreg) (k: code) : res code :=
  match ty, preg_of dst with
  | Tint,    DREG rd => OK (indexed_memory_access (Pldw_rr rd) (Pldw rd) base ofs k)
  | Tsingle, DREG rd => OK (indexed_memory_access (Pfldw_rr rd) (Pfldw rd) base ofs k)
  | Tany32,  DREG rd => OK (indexed_memory_access (Pldw_a_rr rd) (Pldw_a rd) base ofs k)
  | Tint,    AREG rd => OK (indexed_memory_access (Plda_rr rd) (Plda rd) base ofs k)
  | _, _           => Error (msg "Asmgen.loadind")
  end.


Definition storeind (src: mreg) (base: index_reg) (ofs: ptrofs) (ty: typ) (k: code) : res code :=
  match ty, preg_of src with
  | Tint,    DREG src => OK (indexed_memory_access (Pstw_rr src) (Pstw src) base ofs k)
  | Tsingle, DREG src => OK (indexed_memory_access (Pfstw_rr src) (Pfstw src) base ofs k)
  | Tany32,  DREG src => OK (indexed_memory_access (Pstw_a_rr src) (Pstw_a src) base ofs k)
  | Tint,    AREG src => OK (indexed_memory_access (Psta_rr src) (Psta src) base ofs k)
  | _, _           => Error (msg "Asmgen.storeind")
  end.

Definition loadind_ptr (base: index_reg) (ofs: ptrofs) (dst: areg) (k: code) :=
  indexed_memory_access (Plda_rr dst) (Plda dst) base ofs k.

Definition storeind_ptr (src: areg) (base: index_reg) (ofs: ptrofs) (k: code) :=
  indexed_memory_access (Psta_rr src) (Psta src) base ofs k.

(** Translation of memory accesses: loads, and stores. *)

Definition lea rd id ofs k :=
  Pmovh_sa rd id ofs :: Plea_sofs rd rd id ofs :: k.

Definition transl_memory_access
     (mk1: areg -> instruction)
     (mk2: index_reg -> sconst16 -> instruction)
     (mk3: areg -> ident -> ptrofs -> instruction)
     (addr: addressing) (args: list mreg) (k: code)  : res code:=
  match addr, args with
  | Ainstack ofs, nil =>
      OK (indexed_memory_access mk1 mk2 SP ofs k)
  | Aindexed ofs, a1 :: nil =>
      do rs <- areg_of a1;
      if Int.eq ofs Int.zero then
        OK (mk1 rs :: k)
      else
        OK (addimm_addr TMPA rs ofs (mk1 TMPA :: k))
  | Aglobal id ofs, nil =>
      if symbol_bol id ofs then
        OK (Pmovh_sa TMPA id ofs :: (mk3 TMPA id ofs) :: k)
      else
        OK (lea TMPA id ofs (mk1 TMPA :: k))
  | _, _ =>
      Error(msg "Asmgen.transl_memory_access")
  end.

Definition transl_load (chunk: memory_chunk) (addr: addressing)
           (args: list mreg) (dst: mreg) (k: code) :=
  match chunk with
  | Mint8signed =>
      do r <- ireg_of dst;
      transl_memory_access (Pldb_rr r) (Pldb r)  (Pldb_symb r) addr args k
  | Mint8unsigned =>
      do r <- ireg_of dst;
      transl_memory_access (Pldbu_rr r) (Pldbu r) (Pldbu_symb r) addr args k
  | Mint16signed =>
      do r <- ireg_of dst;
      transl_memory_access (Pldh_rr r) (Pldh r)  (Pldh_symb r) addr args k
  | Mint16unsigned =>
      do r <- ireg_of dst;
      transl_memory_access (Pldhu_rr r) (Pldhu r) (Pldhu_symb r) addr args k
  | Mint32 =>
      match preg_of dst with
      | AREG r => transl_memory_access (Plda_rr r) (Plda r) (Plda_symb r) addr args k
      | DREG r => transl_memory_access (Pldw_rr r) (Pldw r) (Pldw_symb r) addr args k
      | _ => Error (msg "Asmgen.transl_load illegal register for Mint32")
      end
  | Mfloat32 =>
      do r <- ireg_of dst;
      transl_memory_access (Pfldw_rr r) (Pfldw r) (Pfldw_symb r) addr args k
  | _ =>
      Error (msg "Asmgen.transl_load")
  end.

Definition transl_store (chunk: memory_chunk) (addr: addressing)
           (args: list mreg) (src: mreg) (k: code) :=
  match chunk with
  | Mint8unsigned =>
      do r <- ireg_of src;
      transl_memory_access (Pstb_rr r) (Pstb r) (Pstb_symb r) addr args k
  | Mint16unsigned =>
      do r <- ireg_of src;
      transl_memory_access (Psth_rr r) (Psth r) (Psth_symb r) addr args k
  | Mint32 =>
      match preg_of src with
      | DREG r => transl_memory_access (Pstw_rr r) (Pstw r) (Pstw_symb r) addr args k
      | AREG r => transl_memory_access (Psta_rr r) (Psta r) (Psta_symb r) addr args k
      | _ => Error (msg "Trying to store data from special register")
      end
  | Mfloat32 =>
      do r <- freg_of src;
      transl_memory_access (Pfstw_rr r) (Pfstw r) (Pfstw_symb r) addr args k
  | _ =>
      Error (msg "Asmgen.transl_store")
  end.

(** Translation of a Mach instruction. *)

Definition transl_instr (f: Mach.function) (i: Mach.instruction)
           (a12_is_parent: bool) (k: code) :=
  match i with
  | Mgetstack ofs ty dst =>
      do dst <- error_single dst;
      loadind SP ofs ty dst k
  | Msetstack src ofs ty =>
      do src <- error_single src;
      storeind src SP ofs ty k
  | Mrestorecallee ofs l => Error (msg "Unsupported instruction Mrestorecallee")
  | Msavecallee ofs l => Error (msg "Unsupported instruction Msavecallee")
  | Mgetparam ofs ty dst =>
      do dst <- error_single dst;
  (* load via the frame pointer if it is valid *)
      do c <- loadind A12 ofs ty dst k;
      OK (if a12_is_parent then c else loadind_ptr SP f.(fn_link_ofs) A12 c)
  | Mop op args res =>
      transl_op op args res k
  | Mload chunk addr args dst =>
      do dst <- error_single dst;
      transl_load chunk addr args dst k
  | Mstore chunk addr args src =>
      do src <- error_single src;
      transl_store chunk addr args src k
  | Mcall sig (inl r) =>
      do r1 <- areg_of r; OK (Pcalli r1 sig :: k)
  | Mcall sig (inr symb) =>
      OK (Pcall symb sig :: k)
  | Mtailcall sig (inl r) =>
      do r1 <- areg_of r;
      OK (Pfreeframe f.(fn_stacksize) f.(fn_link_ofs) :: Pji r1 sig :: k)
  | Mtailcall sig (inr symb) =>
      OK (Pfreeframe f.(fn_stacksize) f.(fn_link_ofs) :: Pj_s symb sig :: k)
  | Mbuiltin ef args res =>
      do res <- restrict_builtin_res res;
      do args <- mmap (@restrict_builtin_arg mreg) args;
      OK (Pbuiltin ef (List.map (map_builtin_arg preg_of) args) (map_builtin_res preg_of res) :: k)
  | Mlabel lbl =>
      OK (Plabel lbl :: k)
  | Mgoto lbl =>
      OK (Pj_l lbl :: k)
  | Mcond cond args lbl =>
      do args <- mmap (@error_single mreg) args;
      transl_cbranch cond args lbl k
  | Mjumptable arg tbl =>
      do r <- ireg_of arg;
      OK (Pbtbl r tbl :: k)
  | Mreturn =>
      OK (Pret f.(fn_stacksize) :: k)
  end.

(** Translation of a code sequence *)

Definition it1_is_parent (before: bool) (i: Mach.instruction) : bool :=
  match i with
  | Msetstack src ofs ty => before
  | Mgetparam ofs ty dst => forallb_rpair (fun x => negb (mreg_eq x P12)) dst
  | Mop op args res => before && forallb_rpair (fun x => negb (mreg_eq x P12)) res
  | _ => false
  end.

(** This is the naive definition that we no longer use because it
  is not tail-recursive.  It is kept as specification. *)

Fixpoint transl_code (f: Mach.function) (il: list Mach.instruction) (it1p: bool) :=
  match il with
  | nil => OK nil
  | i1 :: il' =>
      do k <- transl_code f il' (it1_is_parent it1p i1);
      transl_instr f i1 it1p k
  end.

(** This is an equivalent definition in continuation-passing style
  that runs in constant stack space. *)

Fixpoint transl_code_rec (f: Mach.function) (il: list Mach.instruction)
                         (it1p: bool) (k: code -> res code) :=
  match il with
  | nil => k nil
  | i1 :: il' =>
      transl_code_rec f il' (it1_is_parent it1p i1)
        (fun c1 => do c2 <- transl_instr f i1 it1p c1; k c2)
  end.

Definition transl_code' (f: Mach.function) (il: list Mach.instruction) (it1p: bool) :=
  transl_code_rec f il it1p (fun c => OK c).

(** Translation of a whole function.  Note that we must check
  that the generated code contains less than [2^32] instructions,
  otherwise the offset part of the [PC] code pointer could wrap
  around, leading to incorrect executions. *)

Definition transl_function (f: Mach.function) :=
  do c <- transl_code' f f.(Mach.fn_code) true;
  OK (mkfunction f.(Mach.fn_sig)
        (Pallocframe f.(fn_stacksize) ::
         storeind_ptr A12 SP f.(fn_link_ofs) c)).

Definition transf_function (f: Mach.function) : res Asm.function :=
  if negb (wt_function f) then
    Error (msg "Ill-formed Mach code")
  else
  assertion (negb (f.(fn_retaddr_saved)));
  do tf <- transl_function f;
  if zlt Ptrofs.max_unsigned (list_length_z tf.(fn_code))
  then Error (msg "code size exceeded")
  else OK tf.

Definition transf_fundef (f: Mach.fundef) : res Asm.fundef :=
  transf_partial_fundef transf_function f.

Definition transf_program (p: Mach.program) : res Asm.program :=
  transform_partial_program transf_fundef p.
