#!/usr/bin/env bash

set -euo pipefail

scriptdir=$(dirname $(realpath $0))
envdir=$(dirname $scriptdir)
usage='Usage: ./dev [-help|--help] [target]

Supported targets are:
    aarch64
    arm
    e5500
    ppc
    ppc-diab
    ppcvle-diab
    rv32
    rv64
    tricore
    x32
    x64
'

arg=""

while : ; do
    case ${1:-} in
        "")
            break;;
        -help|--help)
            echo "$usage" 1>&2; exit 0;;
        -*)
            echo "Error: unknown option '$1'." 1>&2
            echo "$usage" 1>&2
            exit 2;;
        *)
            if test -n "$arg"; then echo "$usage" 1>&2; exit 2; fi
            arg="$1";;
    esac
    shift
done

# try interactively get target using fzf
if test -z "$arg"; then
    if command -v fzf >/dev/null; then
        supported_targets="aarch64 arm e5500 ppc ppc-diab ppcvle-diab rv32 rv64 tricore x32 x64"
        commands="all proof check-admitted check-leftovers check-proof clean"
        arg=$(for val in $supported_targets $commands; do echo $val; done | fzf)
    else
        echo "Error: fzf utility not found. Please pass target as argument." 1>&2
        echo "$usage" 1>&2
        exit 2
    fi
fi

function dune () {
    dunecmd=$1; shift
    rest="$@"
    duneflags="--stop-on-first-error"

    if test -z "$dunecmd"; then
        echo "Need command for dune."
        exit 3
    fi
    cmd="dune $dunecmd $duneflags $rest"

    echo $cmd
    # Execute as command to not call this function recursively.
    command $cmd
}

function compile () {
    target=$1

    case "$target" in
        ppc)
            arch_dir="powerpc"
            config_target="ppc-eabi"
            toolprefix="gcc/ppc/bin/powerpc-unknown-eabi-";;
        e5500)
            arch_dir="powerpc"
            config_target="e5500-linux"
            toolprefix="gcc/ppc/bin/powerpc-unknown-linux-gnu-";;
        ppc-diab)
            arch_dir="powerpc"
            config_target="ppc-eabi-diab"
            toolprefix="windriver/5.9.2.0/diab/5.9.2.0/LINUX386/bin/";;
        ppcvle-diab)
            arch_dir="powerpc_vle"
            config_target="ppcvle-eabi-diab"
            toolprefix="windriver/5.9.2.0/diab/5.9.2.0/LINUX386/bin/";;
        arm)
            arch_dir="arm"
            config_target="armv7a-linux"
            toolprefix="gcc/arm/bin/arm-multilib-linux-uclibcgnueabi-";;
        aarch64)
            arch_dir="aarch64"
            config_target="aarch64-linux"
            toolprefix="gcc/aarch64/bin/aarch64-unknown-linux-uclibc-";;
        x32)
            arch_dir="x86_32"
            config_target="x86_32-linux"
            toolprefix="gcc/x86-32/bin/i686-pc-linux-gnu-";;
        x64)
            arch_dir="x86_64"
            config_target="x86_64-linux"
            toolprefix="gcc/x86-64/bin/x86_64-unknown-linux-gnu-";;
        rv32)
            arch_dir="riscV"
            config_target="rv32-linux"
            toolprefix="gcc/riscv/bin/riscv32-unknown-linux-gnu-";;
        rv64)
            arch_dir="riscV"
            config_target="rv64-linux"
            toolprefix="gcc/riscv/bin/riscv64-unknown-linux-gnu-";;
        tricore)
            arch_dir="tricore"
            config_target="tricore-eabi"
            toolprefix="tricore/bin/tricore-elf-";;
        *)
            echo "$usage"
            exit 2;;
    esac

    outdir=out/${target}
    config=${outdir}/Makefile.config
    mkdir -p $outdir ${outdir}/runtime/

    # If it does not already exist, generate default Makefile.config for selected target triple.
    if test ! -e $config; then
        dune exec tools/configure.exe -- "$config_target" -toolprefix "${envdir}/${toolprefix}" -libdir runtime -ignore-coq-version -ignore-ocaml-version -o $config
    fi

    # For ppc-vle we need to add some options to select the correct target, i.e. a powerpc variant that supports VLE and SPE
    if test "$config_target" = "ppcvle-eabi-diab"; then
        echo "Patching Makefile.config for ppc-vle."
        sed -i "s@CASMRUNTIME=das -Xalign-value@CASMRUNTIME=das -Xalign-value -tPPCE200Z420N3VEG:windiss@g" $config
        sed -i "s@_OPTIONS=@_OPTIONS=-tPPCE200Z420N3VEG:windiss @g" $config
    fi

    # Remove files from previous build.
    rm -f ${outdir}/{ccomp,clightgen,compcert.ini} 
    rm -f Makefile.config

    #
    # Build ccomp & clightgen binaries, compcert.ini for target.
    #
    cp $config Makefile.config
    # Build _CoqProject first so that when a proof fails the environment is set up correctly.
    dune build _CoqProject
    # We build the default context here because the OCaml Platform extension for VSCode breaks completely if the default context is not built.
    TARGET_ARCH=$arch_dir dune build ccomp clightgen compcert.ini

    # Compile runtime library
    make -C runtime

    # Backup files into out/$target.
    cp ccomp ${outdir}
    cp clightgen ${outdir}
    cp compcert.ini ${outdir}
    cp runtime/libcompcert.a ${outdir}/runtime/

    make -C runtime clean
}

case "$arg" in
    all)
        dune build @proof
        dune build @extraction
        dune build @compile-ccomp
        dune build @compile-clightgen;;
    proof)
        dune build @proof;;
    check-admitted)
        dune build @check-admitted;;
    check-leftovers)
        dune build @check-leftovers;;
    check-proof)
        dune build @check-proof --no-buffer;;
    clean)
        dune clean
        rm -f out/*/{ccomp,clightgen,compcert.ini,compcert.config,Makefile.config,runtime/libcompcert.a} 
        rm -f ccomp clightgen compcert.ini compcert.config Makefile.config _CoqProject runtime/libcompcert.a;;
    *)
        compile "$arg"
esac
